### ISSUE TITLE
Базовый deploy: basehost0, docker, front container, hub container, upstart

### ISSUE THREAD

**Issue by maizy** [scala-moscow/deploy#1]
- [x] саму машину
  - [x] docker
  - [x] ubuntu мусор
  - [x] ~~ssh ключи для root/user~~ - позже #3 
  - [x] ~~список пакетов, которые нужно ставить всегда свежими (openssh-server, openssh-client, openssl, libtls ..)~~ - вынес в #9
  - [x] ~~/etc/apt/sources.list, удаление сторонних sources.list.d~~ - вынес в #9
- [x] docker images
  - [x] base
  - [x] nginx
    - [x] main configs
    - [x] default host with stub and error pages
    - [x] ~~logs dir~~ - позже #7
- [x] ~~логирование запуска ansible в при постройке image и контейнера~~ - вынес в #4, там описано как пока можно обходиться
- [x] запуск ansible внутри контейнеров
  - [x] как запускать
- [x] контейнеры
  - [x] front - вся статика ~~+ proxy на hub~~
    - [x] ~~делать readonly после запуска на root fs ?~~ -  позже #5
    - [x] проверяем наличие нужной версии конейнера, если есть ничего не делаем
      - [x] составить версию из коммитов стат реп?
    - [x] остановка через upstart существующих контейнеров если есть скрипт
      - upstart всегда с одним названием, типа `docker_container_front`
      - считаем, что upstart остановит нужный контейнер
      - старый конейнер не удаляем
    - [x] создание контейнера через `docker create`
    - [x] создание upstart для нового контейнера
    - [x] запуск через upstart нового контейнера
      - [x] запустить с биндигом портов 80:80
      - [x] ~~папку для логов nginx прокинуть наружу в basehost~~  - позже #7 
      - [x] ~~logrotate силами контейнера (лучше) или basehost (если не получится)~~   - позже #7 
    - [x] запуск ansible-playbook в нём
      - [x] накатить настройки nginx
        - [x] просто по шаблону
        - [x] использовать общую настройку `domain_postfix = ''/'.local'`, подменять для vargant
      - [x] выкатить статику
        - [x] стат. файлы беруться из github реп
        - [x] репы лежат на basehost и из них берётся фикс версия по тагу/коммиту
          - bare repository
          - [x] версию в настройку
        - [x] если нет - создать clone
        - [x] если есть - fetch
        - [x] ~~позже можно сделать прямой проброс машина разработчика -> /vagrant на basehost -> контейнер~~ - #6
        - [x] из репы делается локальный clone в контейнере
        - [x] берутся нужные файлы и копируются в конечное место на которое натравлен nginx
        - [x] временный clone удаляется

  - [x] ~~hub~~ - позже #8
- [x] Создать upstart скрипты
  - docker start X
  - ~~pipework br1 front 192.168.13.X/24~~ - нужно только в #8
- [x] Запустить их
  - [x] Проверить restart basehost
  - [x] убрать автозапуск контейнеров через docker, вместо этого делать самим через upstart - docker по-умолчанию это не делает
- [x] проверять что ansible-playbook успешно запустился в конейнере или image (по коду и наличю фразы, что хосты не найдены)
- [x] почистить скрипты от временных тегов
- [x] проверить с нуля на чистой машине vagrant
- [x] site.yml - для запуска всего
- [x] обновить README
